project_id = "spxdyqdygsmzyngrqxni"

[functions.analyze-po]
verify_jwt = true

[functions.analyze-po-products]
verify_jwt = true

[functions.parse-packing-list]
verify_jwt = true

[functions.send-packing-list]
verify_jwt = true

[functions.quickbooks-init-oauth]
verify_jwt = true

[functions.quickbooks-oauth]
verify_jwt = false

[functions.quickbooks-sync-product]
verify_jwt = true

[functions.quickbooks-sync-invoice]
verify_jwt = true

[functions.quickbooks-sync-vendor-po]
verify_jwt = true

[functions.quickbooks-sync-payment]
verify_jwt = true

[functions.quickbooks-refresh-tokens]
verify_jwt = false

[functions.quickbooks-delete-invoice]
verify_jwt = true

[functions.parse-product-csv]
verify_jwt = true

[functions.upload-inventory]
verify_jwt = true

[functions.send-invoice-email]
verify_jwt = true

[functions.send-vendor-po-email]
verify_jwt = true

[functions.quickbooks-pull-project]
verify_jwt = true

[functions.quickbooks-sync-projects]
verify_jwt = false

[functions.quickbooks-create-project]
verify_jwt = true

[functions.quickbooks-query-projects]
verify_jwt = true

[functions.parse-artwork-zip]
verify_jwt = false

[functions.parse-vendor-packing-list]
verify_jwt = true

[functions.sync-google-sheet]
verify_jwt = true

[functions.quickbooks-push-pending-payments]
verify_jwt = false
