project_id = "spxdyqdygsmzyngrqxni"

[functions.analyze-po]
verify_jwt = true

[functions.analyze-po-products]
verify_jwt = true

[functions.send-packing-list]
verify_jwt = true

[functions.quickbooks-init-oauth]
verify_jwt = true

[functions.quickbooks-oauth]
verify_jwt = false

[functions.quickbooks-sync-product]
verify_jwt = true

[functions.quickbooks-sync-invoice]
verify_jwt = true

[functions.quickbooks-sync-vendor-po]
verify_jwt = true

[functions.quickbooks-sync-payment]
verify_jwt = true

[functions.quickbooks-refresh-tokens]
verify_jwt = false
